---
gettitle: "EC22_024_GF.Rmd"
author: "ECB"
date: "11/15/2022"
output: html_document
---

```{r setup, warning=F}
## Required packages
rm(list=ls())
library("dplyr")
library("ggplot2")
library("ggfortify")
library("tidyr")
library("readr")
library("lubridate")
library("DescTools")
library("knitr")
library("lme4")
library("patchwork")
library("zoo")
library("mgcv")
library("car")
library("pwr")
library("parameters")
library("effectsize")
```

#Data Import
```{r}
#reading file

TSE.data.clean <- read_delim("C:/Users/jens_/OneDrive/Dokumente/Master/Master Thesis/Experiments/Phenomaster/EC22_024_GF_clean.csv", 
                      delim = ",",
                      col_names = TRUE, 
                      col_types = cols(
                          Date = col_date(format = "%y.%m.%d"),
                          Time = col_time(format = "%H:%M:%S"),
                          Box = col_factor(levels=NULL, ordered = FALSE),
                          RER = col_double()
                      ),
                      locale = locale(decimal_mark = ".")
                      )


#importing additional weight variables, weights and genotype
metadata <- read_delim("C:/Users/jens_/OneDrive/Dokumente/Master/Master Thesis/Experiments/Phenomaster/EC22_024_weights_GF.csv", 
                      delim = ",",
                      col_names = TRUE, 
                      col_types = cols(
                        Box = col_factor(levels=NULL, ordered = FALSE)),
                      locale = locale(decimal_mark = "."
                      ))

metadata %>% mutate(genotype = factor(genotype))


#join datasets
TSE.data.clean <- left_join(TSE.data.clean,metadata,by="Box")


```

#Identifying groups. The only distinction is the genotype. There is no change of diet in this experiment.
```{r}
#TSE.data.clean<- TSE.data.clean%>%
 # mutate(diet=if_else(timepoint_h<149,"Low","High"))
```

#Adding day/night identification
```{r}
#create label for nighttime as day.num + 0.5 as well as qualitative variable
TSE.data.clean <- TSE.data.clean %>%
  mutate(day.split = if_else(Time >= dhours(6) & Time < dhours(18), day.num, day.num + 0.5)) %>%
  mutate(circadian.phase = if_else(Time >= dhours(6) & Time < dhours(18), "Diurnal", "Nocturnal")) %>%
  arrange(mouse_ID,day.num,zt)%>%
  group_by(mouse_ID, day.num) %>% mutate(cum.feed.daily = cumsum(Feed),
                                        cum.drink.daily = cumsum(Drink))%>%
  group_by(mouse_ID, day.split) %>% mutate(cum.feed.circ = cumsum(Feed),
                                          cum.drink.circ = cumsum(Drink))
         
#calculate diurnal/nocturnal totals of energy expenditure, drink, feed
circadian.energy <- TSE.data.clean %>%
  group_by(Box, mouse_ID, day.num, day.split, circadian.phase, genotype, av_bm, daily.Feed) %>%
  summarise(
    circadian.Drink = sum(Drink),
    circadian.Feed = sum(Feed),
    circ.EE = as.numeric(AUC(zt, EE_no_BW, method = "trapezoid")),
    circ.VO2 = as.numeric(AUC(zt, VO2_no_BW, method = "trapezoid")))

#summarize daily, average of the energy expenditure/tot 24h
circadian.energy.d <- TSE.data.clean %>%
  group_by(mouse_ID,day.num,genotype) %>%
  summarise(
    circadian.Drink.d = sum(Drink),
    circadian.Feed.d = sum(Feed),
    circ.EE.d = as.numeric(AUC(zt, EE_no_BW, method = "trapezoid")),
    circ.VO2.d = as.numeric(AUC(zt, VO2_no_BW, method = "trapezoid")))

circadian.energy<-left_join(circadian.energy,circadian.energy.d,by=c("mouse_ID","day.num", "genotype"))

#Average EE per mouse over whole experiment
circadian.energy.pm <- circadian.energy %>%  
  group_by(Box, mouse_ID, circadian.phase, av_bm,day.split, genotype) %>%
  summarise(
    circadian.Drink.pm = mean(circadian.Drink),
    circadian.Feed.pm = mean(circadian.Feed),
    circ.EE.pm = mean(circ.EE),
    circ.VO2.pm = mean(circ.VO2),
    circadian.Drink.sd = sd(circadian.Drink),
    circadian.Feed.sd = sd(circadian.Feed),
    circ.EE.sd = sd(circ.EE),
    circ.VO2.sd = sd(circ.VO2)
    )


circadian.energy.pm.d <- circadian.energy %>%
  group_by(mouse_ID, genotype) %>%
  summarise(
    circadian.Drink.pm.d = mean(circadian.Drink.d),
    circadian.Feed.pm.d = mean(circadian.Feed.d),
    circ.EE.pm.d = mean(circ.EE.d),
    circ.VO2.pm.d = mean(circ.VO2.d))

circadian.energy.pm <-left_join(circadian.energy.pm,circadian.energy.pm.d,by=c("mouse_ID", "genotype"))

#make day/night dataframes to facilitate analysis
diurnal.energy <- circadian.energy[which(circadian.energy$circadian.phase == "Diurnal"),]
nocturnal.energy <- circadian.energy[which(circadian.energy$circadian.phase == "Nocturnal"),]

diurnal.energy.pm <- circadian.energy.pm[which(circadian.energy.pm$circadian.phase == "Diurnal"),]
nocturnal.energy.pm <- circadian.energy.pm[which(circadian.energy.pm$circadian.phase == "Nocturnal"),]
```

Exploratory graphs/tables ###
```{r}
#diurnal/nocturnal energy expenditure vs. body mass
ggplot( data = diurnal.energy, aes(x = av_bm, y = circadian.Feed, col = genotype)) +
  geom_point(size = 2) + 
  geom_text(label= diurnal.energy$day.num,color="black",nudge_x=0.25) +
  theme_light() + 
  ylab("Diurnal Energy Expenditure [kcal]") + 
  xlab("Total body mass [g]") + labs(title = "") + 
  labs(color = "Genotype")

ggplot(data=circadian.energy.d, aes(x = day.num, y = circadian.Feed.d, col = mouse_ID), color=genotype) +
  geom_point(size=2) + geom_line() + facet_wrap(~genotype) +
  theme_light() +
  ylab("Daily Food Consumption") + xlab("Day") 

ggplot(data=circadian.energy.d, aes(x = day.num, y = circadian.Drink.d, col = mouse_ID), color=genotype) +
  geom_point(size=2) + geom_line() + facet_wrap(~genotype) +
  theme_light() +
  ylab("Daily Food Consumption") + xlab("Day") 

ggplot( data = nocturnal.energy, aes(x = av_bm, y = circ.EE, col = genotype)) + 
  geom_text(label= nocturnal.energy$day.num,color="black",nudge_x=0.25) +  
  geom_point(size = 2) + 
  theme_light() + 
  ylab("Nocturnal Energy Expenditure [kcal]") + xlab("Total body mass [g]") + labs(color = "Genotype")

```

#Examine/Remove outlier
```{r}
#look at outlier mouse
#View(TSE.data.clean[which(TSE.data.clean$mouseID == "AH8"), c("day.num", "dO2", "dCO2", "RER_no_BW", "Feed", "Drink", "EE_no_BW")])
#high feed values (and cutoff, i.e. variability) are out of the ordinary
#remove outlier
circadian.energy <- filter(circadian.energy, day.split!=6.5)
circadian.energy.pm <- filter(circadian.energy, day.split!=6.5)


diurnal.energy <- circadian.energy[which(circadian.energy$circadian.phase == "Diurnal"),]
nocturnal.energy <- circadian.energy[which(circadian.energy$circadian.phase == "Nocturnal"),]

diurnal.energy.pm <- circadian.energy.pm[which(circadian.energy.pm$circadian.phase == "Diurnal"),]
nocturnal.energy.pm <- circadian.energy.pm[which(circadian.energy.pm$circadian.phase == "Nocturnal"),]

```

Fig 2A: DEEvslean + Suppl Fig 2A: VO2vslean
```{r}
pdf("EEvslean.pdf", width = 8,height = 4)
p1 <- ggplot(diurnal.energy.pm,aes(y=circ.EE.pm,x=lean_total,col=microbiota))+
  geom_smooth(method ="lm",aes(fill=microbiota))+
  geom_linerange(aes(ymin=circ.EE.pm-circ.EE.sd, ymax=circ.EE.pm+circ.EE.sd))+
  geom_point(size=1)+
  scale_color_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Diet")+
  scale_x_continuous(limits = c(19.5,25))+
  scale_y_continuous(limits = c(2.5,6.5))+
  scale_fill_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Diet")+
  theme_bw()+
  theme(panel.grid.minor = element_blank())+
  labs(y="Energy Expenditure [Kcal]", x="Lean body mass [g]")

p2 <- ggplot(nocturnal.energy.pm,aes(y=circ.EE.pm,x=lean_total,col=microbiota))+
  geom_smooth(method ="lm",aes(fill=microbiota))+
  geom_linerange(aes(ymin=circ.EE.pm-circ.EE.sd, ymax=circ.EE.pm+circ.EE.sd))+
  geom_point(size=1)+
  scale_color_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Microbiota")+
  scale_x_continuous(limits = c(19.5,25))+
  scale_y_continuous(limits = c(2.5,6.5))+
  scale_fill_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Microbiota")+
  theme_bw()+
  theme(panel.grid.minor = element_blank())+
  labs(y="Energy Expenditure [Kcal]", x="Lean body mass [g]")

p1+p2+
  plot_layout(guides = "collect")
dev.off()



pdf("VO2vslean.pdf", width = 8,height = 4)
p3 <- ggplot(diurnal.energy.pm,aes(y=circ.VO2.pm,x=lean_total,col=microbiota))+
  geom_smooth(method ="lm",aes(fill=microbiota))+
  geom_linerange(aes(ymin=circ.VO2.pm-circ.VO2.sd, ymax=circ.VO2.pm+circ.VO2.sd))+
  geom_point(size=1)+
  scale_color_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Microbiota")+
  scale_x_continuous(limits = c(19.5,25))+
  scale_y_continuous(limits = c(600,1250))+
  scale_fill_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Microbiota")+
  theme_bw()+
  theme(panel.grid.minor = element_blank())+
  labs(y="VO2 [ml/day]", x="Lean body mass [g]")

p4 <- ggplot(nocturnal.energy.pm,aes(y=circ.VO2.pm,x=lean_total,col=microbiota))+
  geom_smooth(method ="lm",aes(fill=microbiota))+
  geom_linerange(aes(ymin=circ.VO2.pm-circ.VO2.sd, ymax=circ.VO2.pm+circ.VO2.sd))+
  geom_point(size=1)+
  scale_color_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Microbiota")+
  scale_x_continuous(limits = c(19.5,25))+
  scale_y_continuous(limits = c(600,1250))+
  scale_fill_manual(values = c("grey", "#E69F00", "#56B4E9"),
                    name="Microbiota")+
  theme_bw()+
  theme(panel.grid.minor = element_blank())+
  labs(y="VO2 [ml/day]", x="Lean body mass [g]")

p3+p4+
  plot_layout(guides = "collect")
dev.off()


#p values for linear relationship between EEvslean or VO2vslean

mod3.diurnal.pm <- lm(circ.EE.pm ~ lean_total, data = subset(diurnal.energy.pm,microbiota=="SPF"))
mod3.nocturnal.pm <- lm(circ.EE.pm ~ lean_total, data = subset(nocturnal.energy.pm,microbiota=="SPF"))

summary(mod3.diurnal.pm)
summary(mod3.nocturnal.pm)


mod3.diurnal.pm <- lm(circ.VO2.pm ~ lean_total, data = subset(diurnal.energy.pm,microbiota=="SPF"))
mod3.nocturnal.pm <- lm(circ.VO2.pm ~ lean_total, data = subset(nocturnal.energy.pm,microbiota=="SPF"))

summary(mod3.diurnal.pm)
summary(mod3.nocturnal.pm)

```

Regression-based normalization
```{r}

#Diurnal / Nocturnal EE or VO2 (lean + fat model)
mod1.diurnal.pm <- lm(circ.EE.pm ~ lean_total + microbiota + fat.dissect, data = diurnal.energy.pm)
mod1.nocturnal.pm <- lm(circ.EE.pm ~ lean_total + microbiota + fat.dissect, data = nocturnal.energy.pm)

summary(mod1.diurnal.pm)
summary(mod1.nocturnal.pm)

mod4.diurnal.pm <- lm(circ.VO2.pm ~ lean_total + microbiota + fat.dissect, data = diurnal.energy.pm)
mod4.nocturnal.pm <- lm(circ.VO2.pm ~ lean_total + microbiota + fat.dissect, data = nocturnal.energy.pm)

summary(mod4.diurnal.pm)
summary(mod4.nocturnal.pm)

#daily EE or VO2
mod1.daily.pm <- lm(circ.EE.pm.d ~ lean_total + microbiota + fat.dissect, data = diurnal.energy.pm)
mod2.daily.pm <- lm(circ.VO2.pm.d ~ lean_total + microbiota + fat.dissect, data = diurnal.energy.pm)

summary(mod1.daily.pm)
summary(mod2.daily.pm)


```


#Fig Supp: Raw EE vs t
```{r}
#average RER per timepoint per mouse
avg.rawEE.pm <- TSE.data.clean %>%
  group_by(mouse_ID,zt,genotype) %>%
  summarise(
    avg.rawEE.zt = mean(EE_no_BW),
    avg.rawEE.zt.sd = sd(EE_no_BW),
    avg.Feed = mean(Feed[which(Feed > 0)]),
    avg.cum.feed.daily = mean(cum.feed.daily),
    avg.cum.feed.daily.sd = sd(cum.feed.daily),
    )

avg.rawEE.pm.t <- TSE.data.clean %>%
  group_by(mouse_ID,genotype,timepoint_clean_h) %>%
  summarise(
    avg.rawEE.t = mean(EE_no_BW),
    avg.rawEE.t.sd = sd(EE_no_BW),
    avg.Feed = mean(Feed[which(Feed > 0)]),
    avg.cum.feed.daily = mean(cum.feed.daily),
    avg.cum.feed.daily.sd = sd(cum.feed.daily),
    )

#RER during the circadian cycle
prawEE<-ggplot(data = avg.rawEE.pm)+
  coord_cartesian(ylim = c(0.29,0.7), xlim = c(0,24))+ #scale_y_limit drop datapoints, coord_cartesian doesnt
  scale_x_continuous(breaks = c(0,6,12,18,24),expand = c(0,0))+
  annotate("rect", ymin = -Inf, ymax = Inf, xmin=12, xmax=24, alpha = 0.2,fill="grey")+
  annotate("rect", ymin = -Inf, ymax = 0.29, xmin=0, xmax=12,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.29, xmin=12, xmax=24,fill="black",col="black")+
  theme_bw() +
  theme(panel.grid.major.x=element_blank())+
  aes(x = zt, y = avg.rawEE.zt, fill = genotype, col=genotype)+
  geom_smooth(size = 1, method = "gam", formula = y ~ s(x, bs = "cs")) + 
  scale_fill_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") +
  scale_color_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") + 
  labs(y="Energy Expenditure [Kcal]", x="Zeitgeber Time [h]")

pdf("RawEE_GF.pdf",width = 5,height = 4)
prawEE
dev.off()

prawEE_t <- ggplot(avg.rawEE.pm.t)+
  #coord_cartesian(ylim = c(0,0.8), xlim = c(0,108))+ #scale_y_limit drop datapoints, coord_cartesian doesnt
  aes(x = timepoint_clean_h, y = avg.rawEE.t, fill = genotype, col=genotype)+
  scale_y_continuous(limit=c(0.15,0.6))+
  scale_x_continuous(limit=c(0,120),breaks = c(0,12,24,36,48,60,72,84,96,108,120))+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=0, xmax=12,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=12, xmax=24,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=24, xmax=36,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=36, xmax=48,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=48, xmax=60,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=60, xmax=72,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=72, xmax=84,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=84, xmax=96,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=96, xmax=108,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=108, xmax=120,fill="black",col="black")+
  geom_line(size=0.2)+
  theme_bw()+
  theme(panel.grid.minor.x=element_blank())+
  scale_fill_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") +
  scale_color_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") + 
  labs(y="Energy Expenditure [Kcal]", x="Time [h]")+
  facet_grid(mouse_ID~.)


pdf("RawEE_t_GF.pdf",width = 8,height = 4)
prawEE_t
dev.off()


```
#Fig 3A: RER
```{r echo=FALSE}
#average RER per timepoint per mouse
avg.RER.pm <- TSE.data.clean %>%
  group_by(mouse_ID,genotype,zt) %>%
  summarise(
    avg.RER.zt = mean(RER_no_BW),
    avg.RER.zt.sd = sd(RER_no_BW),
    avg.Feed = mean(Feed[which(Feed > 0)]),
    avg.cum.feed.daily = mean(cum.feed.daily),
    avg.cum.feed.daily.sd = sd(cum.feed.daily),
    )

avg.rawRER.pm.t <- TSE.data.clean %>%
  group_by(mouse_ID,genotype,timepoint_clean_h) %>%
  summarise(
    avg.rawRER.t = mean(RER_no_BW),
    )

prawRER_t <- ggplot(avg.rawRER.pm.t)+
  coord_cartesian(ylim = c(0,1), xlim = c(0,120))+  
  aes(x = timepoint_clean_h, y = avg.rawRER.t, fill = genotype, col=genotype)+
  scale_y_continuous(limit=c(0,1))+
  scale_x_continuous(limit=c(0,120),breaks = c(0,12,24,36,48,60,72,84,96,108,120))+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=0, xmax=12,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=12, xmax=24,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=24, xmax=36,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=36, xmax=48,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=48, xmax=60,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=60, xmax=72,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=72, xmax=84,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=84, xmax=96,fill="black",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=96, xmax=108,fill="white",col="black")+
  annotate("rect", ymin = -Inf, ymax = 0.15, xmin=108, xmax=120,fill="black",col="black")+
  geom_line(size=0.2)+
  theme_bw()+
  theme(panel.grid.minor.x=element_blank())+
  scale_fill_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") +
  scale_color_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") + 
  labs(y="Energy Expenditure [Kcal]", x="Time [h]")+
  facet_grid(mouse_ID~.)
prawRER_t

avg.RER.pm.c <- TSE.data.clean %>%
  group_by(mouse_ID,genotype,circadian.phase) %>%
  summarise(
    avg.RER.zt = mean(RER_no_BW),
    avg.RER.zt.sd = sd(RER_no_BW),
    avg.Feed = mean(Feed[which(Feed > 0)]),
    avg.cum.feed.daily = mean(cum.feed.daily),
    avg.cum.feed.daily.sd = sd(cum.feed.daily),
    )

#RER during the circadian cycle
  pRER<-ggplot(data = avg.RER.pm)+
   coord_cartesian(ylim = c(0.65,1), xlim = c(0,24))+ 
    scale_x_continuous(breaks = c(0,6,12,18,24),expand = c(0,0))+
    annotate("rect", ymin = -Inf, ymax = Inf, xmin=12, xmax=24, alpha = 0.2,fill="grey")+
    annotate("rect", ymin = -Inf, ymax = 0.65, xmin=0, xmax=12,fill="white",col="black")+
    annotate("rect", ymin = -Inf, ymax = 0.65, xmin=12, xmax=24,fill="black",col="black")+
    theme_bw() +
    theme(panel.grid.major.x=element_blank())+
    aes(x = zt, y = avg.RER.zt, fill = genotype, col=genotype) + 
      geom_smooth(size = 1, method = "loess",  span = 0.7) + 
    scale_fill_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") +
    scale_color_manual(values=c("grey50", "#E69F00", "#56B4E9"),name="Genotype") + 
    labs(y="Respiratory Exchange Ratio", x="Zeitgeber Time [h]")
  pRER
  
  pRERd <- ggplot(subset(avg.RER.pm.c,circadian.phase=="Diurnal"))+
    aes(x = genotype, y = avg.RER.zt, fill = genotype)+
    geom_boxplot(outlier.shape = NA)+
    #scale_fill_manual(values = c("grey", "#E69F00", "#56B4E9"),name="Genotype")+
    scale_y_continuous(limits = c(0.67,0.85))+
    geom_point(position = position_jitter(width = 0.1),
               col="black",
               alpha=0.5)+
    theme_bw() +
    theme(panel.grid.major.x=element_blank(),legend.position = "None")+
    labs(y="Respiratory Exchange Ratio", x="")
  pRERd
  
  pRERn <- ggplot(subset(avg.RER.pm.c,circadian.phase=="Nocturnal"))+
    aes(x = genotype, y = avg.RER.zt, fill = genotype)+
    geom_boxplot(outlier.shape = NA)+
    #scale_fill_manual(values = c("grey", "#E69F00", "#56B4E9"),name="Genotype")+
    scale_y_continuous(limits = c(0.67,0.85))+
    geom_point(position = position_jitter(width = 0.1),
               col="black",
               alpha=0.5)+
    #geom_text(aes(x=genotype, y = avg.RER.zt, label = mouse_ID, color="black",nudge_x=0.25)) +
    theme_bw() +
    theme(panel.grid.major.x=element_blank(),legend.position = "None")+
    labs(y="Respiratory Exchange Ratio", x="")
  pRERn
  
  pdf("RER_all_GF.pdf",width = 5,height = 4)
  pRER
  dev.off()
  
  pdf("RER_dayvsnight_GF.pdf",width = 4,height = 4)
  pRERd+pRERn
  dev.off()

#mod1 <- aov(data=subset(avg.RER.pm.c,circadian.phase=="Diurnal"), avg.RER.zt~microbiota)
#mod2 <- aov(data=subset(avg.RER.pm.c,circadian.phase=="Nocturnal"), avg.RER.zt~microbiota)

#TukeyHSD(mod1)
#TukeyHSD(mod2)
```

#Fig 3B: Circadian Food Intake
```{r}
zt_lower <- c(0,6,12,18)
zt_upper <- c(6,12,18,24)

#generate plots. MAKE SURE TO CHECK Y-AXIS LIMITS AFTER GENERATING
for(i in 1:length(zt_lower)){
#calculate values
feed.custom <- TSE.data.clean%>%
  filter(zt>= zt_lower[i] & zt <= zt_upper[i]) %>%
  group_by(mouse_ID,genotype,day.num) %>%
  summarise(
    feed.freq = length(which(Feed > 0)),
    avg.portion = mean(Feed[which(Feed > 0)]),
    avg.portion.sd = sd(Feed[which(Feed > 0)]),
    tot.feed = sum(Feed))

#remove NA
feed.custom[is.na(feed.custom)] <- 0

#creating per mouse average dataset
feed.custom.pm <- feed.custom %>%
  group_by(mouse_ID,genotype) %>%
  summarise(feed.freq.pm = mean(feed.freq),
            feed.freq.sd = sd(feed.freq),
            avg.portion.pm = mean(avg.portion),
            avg.portion.pm.sd = sd(avg.portion),
            tot.feed.pm = mean(tot.feed),
            tot.feed.pm.sd = sd(tot.feed)) %>%
  mutate(avg.portion.pm.norm = avg.portion.pm/lean_total,
         avg.portion.pm.norm.sd = sd(avg.portion.pm/lean_total),
          tot.feed.pm.norm = feed.freq.pm*avg.portion.pm.norm,
          zt_group=1)

feed.custom.pm <- feed.custom.pm%>%
  group_by(zt_group)%>%
  mutate(avLBM=mean(genotype))

#total feed
assign(paste("feed.tot", i, sep = ""),
ggplot(feed.custom.pm, aes(x = genotype, y = tot.feed.pm, fill = genotype)) +
  geom_boxplot(outlier.shape = NA) + 
  scale_fill_manual(values=c("grey", "#E69F00", "#56B4E9"), name = "Genotype") +
  scale_y_continuous(limits= c(0,2.5)) +
  geom_point(position = position_jitter(width = 0.1),col="black",alpha=0.5) + 
  theme_bw() +
  theme(panel.grid.major.x=element_blank(),plot.title = element_blank(),legend.position = "None") +
  labs(y="Food Intake [g]", x="", title = paste("Zeitgeber ", as.character(zt_lower[i]), "-", as.character(zt_upper[i]),sep = "")))

#tot.feed.custom.pm.lm <- lm(tot.feed.pm ~ lean_total + microbiota, data = feed.custom.pm)
#print(summary(tot.feed.custom.pm.lm))
#feed.custom.pm$resid.feed <- resid(tot.feed.custom.pm.lm)

feed.custom.pm <- feed.custom.pm%>%
  mutate(
    adj.Feed = case_when(
      microbiota=="GF" ~ coef(tot.feed.custom.pm.lm)[1]+coef(tot.feed.custom.pm.lm)[2]*avLBM + resid.feed,
      microbiota=="Oligo" ~ (coef(tot.feed.custom.pm.lm)[1]+coef(tot.feed.custom.pm.lm)[3])+coef(tot.feed.custom.pm.lm)[2]*avLBM + resid.feed,
      microbiota=="SPF" ~ (coef(tot.feed.custom.pm.lm)[1]+coef(tot.feed.custom.pm.lm)[4])+coef(tot.feed.custom.pm.lm)[2]*avLBM + resid.feed))

#regression normalized feed
assign(paste("adj.feed.tot", i, sep = ""),
ggplot(feed.custom.pm, aes(x = microbiota, y = adj.Feed, fill = microbiota)) +
  geom_boxplot(outlier.shape = NA) + 
  scale_fill_manual(values=c("grey", "#E69F00", "#56B4E9"), name = "Genotype") +
  scale_y_continuous(limits= c(0,2.5)) +
  geom_point(position = position_jitter(width = 0.1),col="black",alpha=0.5)+ 
  theme_bw() +
  theme(panel.grid.major.x=element_blank(),plot.title = element_blank(),legend.position = "None") +
  labs(y="Food Intake [g]", x="", title = paste("Zt ", as.character(zt_lower[i]), "-", as.character(zt_upper[i]),sep = "")))

write.csv(feed.custom.pm,paste0("supptab_",i,".csv"))

mod1 <- aov(data=feed.custom.pm, tot.feed.pm~microbiota)
print(TukeyHSD(mod1))

mod2 <- aov(data=feed.custom.pm, adj.Feed~microbiota)
print(TukeyHSD(mod2))
}

pdf("Circ_feed_total.pdf",width = 8,height = 4)
feed.tot1+feed.tot2+feed.tot3+feed.tot4+plot_layout(nrow = 1)
dev.off()

pdf("Circ_feed_adj.pdf",width = 8,height = 4)
adj.feed.tot1+adj.feed.tot2+adj.feed.tot3+adj.feed.tot4+plot_layout(nrow = 1)
dev.off()

```
